---
title: "XX"
author: 
  - "E. Fernando Cagua^1^ ([efc29@uclive.ac.nz](mailto:efc29@uclive.ac.nz))"
  - "Audrey Lustig^2^ ([audrey.lustig@canterbury.ac.nz](audrey.lustig@canterbury.ac.nz))"
  - "Jason M. Tylianakis^1^ ([jason.tylianakis@canterbury.ac.nz](jason.tylianakis@canterbury.ac.nz))"
  - "Daniel B. Stouffer^1^ ([daniel.stouffer@canterbury.ac.nz](daniel.stouffer@canterbury.ac.nz))"
# bibliography: phd-bibliography/pollen-competition.bib
csl: ecology-letters.csl
output: #word_document
  bookdown::pdf_document2:
    # base_format: rticles::peerj_article
    keep_tex: yes
    number_sections: false
toc: false
fontsize: 11pt
# classoption: a4paper
geometry: 
  - textwidth=33em
  - textheight=48\baselineskip
header-includes:
  - \usepackage{booktabs}
  - \usepackage{setspace}
  - \usepackage{lineno}
  - \usepackage{xr}
  - \usepackage[utf8]{inputenc}
  - \newcommand{\R}[1]{\label{#1}\linelabel{#1}}
  - \newcommand{\lr}[1]{page~\pageref{#1}, line~\lineref{#1}}
  - \externaldocument[S-]{supp-info}
  - \usepackage[export]{adjustbox}
---

\linenumbers
\doublespacing

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, 
                      warning = FALSE, dpi = 300)

loadd(abs_wordcount, msc_wordcount, n_displays, n_references, keywords)
```
 
^1^ Centre for Integrative Ecology, School of Biological Sciences, University of Canterbury, Private Bag 4800, Christchurch 8041, New Zealand

^2^ Geospatial Research Institute, University of Canterbury, Private Bag 4800, Christchurch 8041, New Zealand

**Running title:** XX

**Keywords:** `r keywords`

**Type of article:** XX

**Number of words:** `r abs_wordcount$n_words_stri` in abstract; `r format(round(msc_wordcount$n_words_stri), big.mark = ",")` in main text.

**Number of displays:** `r n_displays$figures` figures; `r n_displays$tables` tables; `r n_displays$text_boxes` text boxes.

**Number of references:** `r n_references`

**Author for correspondence:** E. Fernando Cagua (+64 20 4026 8153).

**Data accessibility:** Data supporting the results will be accessible in an appropriate data repository after publication. The DOI will be included here.

**Author contributions:** XX

\clearpage

# Abstract

`r paste(drake::readd(abstract), collapse = "")`

\clearpage

# Introduction

# Methods

# Results

# Discussion 

# Acknowledgements

`r paste(drake::readd(acknowledgements), collapse = "")`

# References
