---
title: "Environmental stress affects niche breadth in plant-pollinator communities"
subtitle: "Supplementary information"
author: "E. Fernando Cagua, Hugo J. Marrero, Jason M. Tylianakis, Daniel B. Stouffer"
bibliography: 
  - bibliography.bib
  - int-bibliography.bib
# csl: pnas.csl
output: 
  bookdown::pdf_document2:
    # base_format: rticles::peerj_article
    keep_tex: yes
    number_sections: false
toc: false
fontsize: 11pt
# classoption: a4paper
geometry: 
  - textwidth=33em
  - textheight=48\baselineskip
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{xcolor}
  - \usepackage{setspace}
  - \usepackage{caption}
editor_options: 
  chunk_output_type: console
---

\onehalfspacing
\captionsetup[table]{skip=10pt}

<!-- To add an S before each figure and table -->
\renewcommand\thefigure{S\arabic{figure}}    
\setcounter{figure}{0}   

\renewcommand\thetable{S\arabic{table}}    
\setcounter{table}{0}   

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, 
                      warning = FALSE)
options(xtable.comment = FALSE, 
        xtable.caption.placement = 'bottom',
        xtable.size = 'small',
        booktabs = TRUE, 
        knitr.kable.NA = "-")
library(dplyr)
```


```{r tab-manual-name-corrections}
loadd(spp, manual_name_corrections)
manual_name_corrections %>%
  inner_join(spp, by = c("queried_sp_name" = "sp_name")) %>%
  distinct(queried_sp_name, sp_name, guild) %>%
  filter(!is.na(sp_name)) %>%
  arrange(guild, queried_sp_name, sp_name) %>%
  mutate(sp_name = tidyr::replace_na(sp_name, "no replacement found"), 
         sp_name = kableExtra::cell_spec(sp_name, italic = TRUE), 
         guild = if_else(guild == "pla", "plant", "pollinator")) %>%
  knitr::kable(caption = "Manually corrected canonnical names. More than one correct name have been included when an accepted/valid synonym the cannonical name exists.", 
               col.names = c("incorrect name", "corrected name", "guild"),
               booktabs = TRUE, 
               escape = F) %>%
  kableExtra::kable_styling(font_size = 8) %>%
  kableExtra::collapse_rows(1, latex_hline = "none", valign = "top")
```

```{r eval = FALSE, tab-sp-synonym-reasons}
sp_with_synonyms %>%
  filter(!is.na(itis_reason)) %>%
  group_by(queried_sp_name) %>%
  summarise(itis_reason = first(itis_reason)) %>%
  group_by(itis_reason) %>%
  count(sort = T) %>%
  knitr::kable("latex", 
               col.names = c("reason of species alternative name", "n"), 
               caption = "tablesita", 
               booktabs = TRUE) %>%
  kableExtra::kable_styling(font_size = 8) %>%
  kableExtra::collapse_rows(columns = 1)
```
